In [1]:
import shutil
import os
import cv2 as cv
import glob
import numpy as np


# đọc file ET01

# Đọc file ET02b

In [ ]:
# path="D:\DatasetJapanese\ET1\katagana"
pathDataset="D:\DatasetJapanese\ET1\kata_dataset"
pathDatatest="D:\DatasetJapanese\ET1\kata_datatest"
# def copydataset(path, soLuongAnhMoiLabel)

katagana=os.listdir(path)
# print("a",os.path.join(pathDataset,"hi"))
# # print(katagana)
# c=os.listdir(path+"\\"+katagana[0])
# print(os.path.dirname(path))


for alphabet_k in katagana:
    i=0
    
    path_copy1=path+'\\'+alphabet_k;
    dictionary = os.listdir(path+'\\'+alphabet_k)
    
    # set duong dan cho muc
    alphabet_path_dataset = pathDataset+'\\'+alphabet_k
    alphabet_path_datatest = pathDatatest+'\\'+alphabet_k

    
    #tao file neu chua ton tai
    if not os.path.exists(alphabet_path_dataset):
        os.makedirs(alphabet_path_dataset)
    if not os.path.exists(alphabet_path_datatest):
        os.makedirs(alphabet_path_datatest)
        
    for file in dictionary:
        path_copy = path_copy1+'\\'+file
        path_paste = alphabet_path_dataset+'\\'+file
        if i<=500:
            shutil.copy2(path_copy,path_paste)
            
        elif (i>500 and i<=750):
            path_copy2 = path_copy1+'\\'+file
            path_paste2 = alphabet_path_datatest+'\\'+file
            shutil.copy2(path_copy2,path_paste2)
        else:
            break
        i+=1
        
        

In [45]:




pathDataset_test="D:\DatasetJapanese\ET1"\
# truy cap vao file theo duong dan: '*' de truy cap tat ca file trong duong dan
path = os.path.join(pathDataset_test,"kata_datatest", "a_k", '*')
print(path)


#get all dict  from D:\DatasetJapanese\ET1\kata_datatest\a_k into a
a = glob.glob(path) #chuan hoa duong dan
#print("a:\n",a)

img =cv.imread(a[0])
print(np.max(img[62,:,0]))
print(np.argmax(img[62,:,0]))

a=np.multiply(img, 1.0 / 255.0)
print(np.max(a[62,:,0]))
print(np.argmax(a[62,:,0]))

x=np.arange(1,13).reshape(3,4)
print("shape[0]",x.shape[0])
print(x)
print(x.shape)
y=np.array([1,2,3,4])
print("yshape: ",y.shape)
y=y.reshape(1,4)
print(y.reshape(1,4))
print("y reshape: ",y.shape)
print(np.multiply(y,x))
print(x*2)

D:\DatasetJapanese\ET1\kata_datatest\a_k\*
80
24
0.313725490196
24
shape[0] 3
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
yshape:  (4,)
[[1 2 3 4]]
y reshape:  (1, 4)
[[ 1  4  9 16]
 [ 5 12 21 32]
 [ 9 20 33 48]]
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [40]:
# xử lý với cv2 đường dẫn cần chuẩn: D:\\abc\\abc\\
path1="D:\\DatasetJapanese\\ET1\\kata_datatest\\a_k\\00502.png" #cai nay su dung dc
path2="D:\DatasetJapanese\ET1\kata_datatest\a_k\00502.png"# cai nay khong su dung duoc trong cv2
img =cv.imread(a[0])

print(img.shape)
for i in a: # su dung i thi duoc, con a[0] thi khong duoc
    img =cv.imread(i)

#     print(img.shape)
    # resize =cv.resize(img,(64,64))
    # print(resize[:,0,0])
    # cv.imshow('image',resize)
    # cv.waitKey(0)
    # cv.destroyAllWindows()

TypeError: bad argument type for built-in operation